// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEOoFwVNARv98sQSSxqcwRowhE5TSJbuw',
    appId: '1:622179408431:web:d0538e62d8865258fd84da',
    messagingSenderId: '622179408431',
    projectId: 'app-from-youtube',
    authDomain: 'app-from-7f4c3.firebaseapp.com',
    storageBucket: 'app-from-youtube.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQ5dtVTf-pwH3kGRgeFRdCSk2XYkZsx4',
    appId: '1:622179408431:android:a7073170bf1192cafd84da',
    messagingSenderId: '622179408431',
    projectId: 'app-from-youtube',
    storageBucket: 'app-from-youtube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsMo7CVFITIrM6wgO1b1NbZNmua720rf0',
    appId: '1:622179408431:ios:d4e31df04d83697ffd84da',
    messagingSenderId: '622179408431',
    projectId: 'app-from-youtube',
    storageBucket: 'app-from-youtube.appspot.com',
    iosClientId: '622179408431-81ksq21fnukujl4cidqde151rueraaoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsMo7CVFITIrM6wgO1b1NbZNmua720rf0',
    appId: '1:622179408431:ios:d4e31df04d83697ffd84da',
    messagingSenderId: '622179408431',
    projectId: 'app-from-youtube',
    storageBucket: 'app-from-youtube.appspot.com',
    iosClientId: '622179408431-81ksq21fnukujl4cidqde151rueraaoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
